# JettraKanban local defaults (do not commit secrets)
# You can override these with env vars:
# GITHUB_USERNAME, GITHUB_PASSWORD, GITHUB_TOKEN and GITHUB_PROJECT_URL

github.username=
github.password=
github.token=
github.projectUrl=
